#include<stdio.h>
#include<string.h>
int main()
{
 char str[250];
 int i,j,k,n,t,length,max,ca,cb,cc,cd,ce,cf,cg,ch,ci,cj,ck,cl,cm,cn,co,cp,cq,cr,cs,ct,cu,cv,cw,cx,cy,cz;
 scanf("%d%*c",&t);
 while(t--)
 {
  gets(str);
  max=0;
  ca=0,cb=0,cc=0,cd=0,ce=0,cf=0,cg=0,ch=0,ci=0,cj=0,ck=0,cl=0,cm=0,cn=0,co=0,cp=0,cq=0,cr=0,cs=0,ct=0,cu=0,cv=0,cw=0,cx=0,cy=0,cz=0;
  length=strlen(str);
  for(i=0;i<length;i++)
  {
   if(str[i]=='A'||str[i]=='a')
   {
        ca++;
    if(ca>max)
        max=ca;
    continue;
   }
   if(str[i]=='B'||str[i]=='b')
   {
        cb++;
    if(cb>max)
            max=cb;
    continue;
   }
   if(str[i]=='C'||str[i]=='c')
           {
        cc++;
    if(cc>max)
            max=cc;
    continue;
   }
   if(str[i]=='D'||str[i]=='d')
       {
        cd++;
    if(cd>max)
            max=cd;
    continue;
   }
   if(str[i]=='E'||str[i]=='e')
       {
        ce++;
    if(ce>max)
            max=ce;
    continue;
       }
   if(str[i]=='F'||str[i]=='f')
       {
        cf++;
    if(cf>max)
            max=cf;
    continue;
   }
   if(str[i]=='G'||str[i]=='g')
       {
        cg++;
    if(cg>max)
            max=cg;
    continue;
   }
   if(str[i]=='H'||str[i]=='h')
       {
        ch++;
    if(ch>max)
            max=ch;
    continue;
   }
   if(str[i]=='I'||str[i]=='i')
       {
        ci++;
    if(ci>max)
            max=ci;
    continue;
   }
   if(str[i]=='J'||str[i]=='j')
       {
        cj++;
    if(cj>max)
            max=cj;
    continue;
   }
   if(str[i]=='K'||str[i]=='k')
       {
        ck++;
    if(ck>max)
            max=ck;
    continue;
   }
   if(str[i]=='L'||str[i]=='l')
       {
        cl++;
    if(cl>max)
            max=cl;
    continue;
   }
   if(str[i]=='M'||str[i]=='m')
       {
        cm++;
    if(cm>max)
            max=cm;
    continue;
   }
   if(str[i]=='N'||str[i]=='n')
       {
        cn++;
    if(cn>max)
            max=cn;
    continue;
   }
   if(str[i]=='O'||str[i]=='o')
       {
        co++;
    if(co>max)
            max=co;
    continue;
   }
   if(str[i]=='P'||str[i]=='p')
       {
        cp++;
    if(cp>max)
            max=cp;
    continue;
   }
   if(str[i]=='Q'||str[i]=='q')
    {
        cq++;
    if(cq>max)
            max=cq;
    continue;
   }
   if(str[i]=='R'||str[i]=='r')
   {
        cr++;
    if(cr>max)
            max=cr;
    continue;
   }
   if(str[i]=='S'||str[i]=='s')
   {
        cs++;
    if(cs>max)
            max=cs;
    continue;
   }
   if(str[i]=='T'||str[i]=='t')
   {
        ct++;
    if(ct>max)
            max=ct;
    continue;
   }
   if(str[i]=='U'||str[i]=='u')
       {
        cu++;
    if(cu>max)
            max=cu;
    continue;
   }
   if(str[i]=='V'||str[i]=='v')
       {
        cv++;
    if(cv>max)
            max=cv;
    continue;
   }
   if(str[i]=='W'||str[i]=='w')
       {
        cw++;
    if(cw>max)
            max=cw;
    continue;
   }
   if(str[i]=='X'||str[i]=='x')
       {
        cx++;
    if(cx>max)
            max=cx;
    continue;
   }
   if(str[i]=='Y'||str[i]=='y')
       {
        cy++;
    if(cy>max)
            max=cy;
    continue;
   }
   if(str[i]=='Z'||str[i]=='z')
       {
        cz++;
    if(cz>max)
            max=cz;
    continue;
   }
  }
    if(ca==max)
    printf("a");
    if(cb==max)
    printf("b");
    if(cc==max)
    printf("c");
    if(cd==max)
    printf("d");
    if(ce==max)
    printf("e");
    if(cf==max)
    printf("f");
    if(cg==max)
    printf("g");
    if(ch==max)
    printf("h");
    if(ci==max)
    printf("i");
    if(cj==max)
    printf("j");
    if(ck==max)
    printf("k");
    if(cl==max)
    printf("l");
    if(cm==max)
    printf("m");
    if(cn==max)
    printf("n");
    if(co==max)
    printf("o");
    if(cp==max)
    printf("p");
    if(cq==max)
    printf("q");
    if(cr==max)
    printf("r");
    if(cs==max)
    printf("s");
    if(ct==max)
    printf("t");
    if(cu==max)
    printf("u");
    if(cv==max)
    printf("v");
    if(cw==max)
    printf("w");
    if(cx==max)
    printf("x");
    if(cy==max)
    printf("y");
    if(cz==max)
    printf("z");
  printf("\n");
 }
 return 0;
}
